name: Download Fotos from Email

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip 
        pip install Pillow
        pip install pyheif

    - name: Run Python script
      run: python get_fotos.py
      env:
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    - name: Run generate_html.py
      run: python generate_html.py
      
    - name: Commit and push changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add pagina.html
        git add contents/fotos/* 
        git add contents/captions.csv
        git commit -m "Get Fotos From E-mail and Update Slideshow" || echo "No changes to commit"
        git push
