name: Download Fotos from Email

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Dit draait het script elk uur. Wijzig dit volgens je eigen behoeften

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        # Voeg hier eventuele andere afhankelijkheden toe die je script nodig heeft

    - name: Run Python script
      run: python get_fotos.py
      env:
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    - name: Commit and push changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add pagina.html
        git commit -m "Get Fotos From E-mail" || echo "No changes to commit"
        git push
